eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
    
microservice:
  payment-service:
    endpoints:
      endpoint:
        uri: http://PAYMENT-SERVICE/payment/doPayment
  order-service:
    endpoints:
      endpoint:
        uri: http://ORDER-SERVICE/order/bookOrder 
        
  product-application:
    endpoints:
      endpoint:
        uri: http://PRODUCT_APPLICATION/api/cigna/save/product 
        uri: http://PRODUCT_APPLICATION/api/cigna/find/all
        uri: http://PRODUCT_APPLICATION/api/cigna/find/product/byid 
       
        
